name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.x

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Release
        run: GOPROXY=proxy.golang.org go list -m github.com/kachaje/libsvm-go@${{env.RELEASE_VERSION}}
