name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.x

      - name: Build
        run: go build -v ./...

      - name: Test
        working-directory: ./v3
        run: go test -v ./...
      
  release-on-push:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOPROXY: proxy.golang.org 
    steps:
      - id: release

      - name: Release
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.x
        run: |
          VERSION=`gh api /repos/kachaje/libsvm-go/tags --jq .[0].name | awk -F. '{OFS="."; $NF+=1; print $0}'`

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/kachaje/libsvm-go/releases \
            -f "tag_name=$VERSION" -f 'target_commitish=main' -f "name=$VERSION" -f 'body=New release' -F "draft=false" -F "prerelease=false" -F "generate_release_notes=false"

          go list -m github.com/kachaje/libsvm-go/v3@${VERSION}
