name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOPROXY: proxy.golang.org 
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.x

      - name: Build
        run: go build -v ./...

      - name: Test
        working-directory: ./v3
        run: go test -v ./...
      
      - name: Release
        run: |
          VERSION=`gh api /repos/kachaje/libsvm-go/tags --jq .[0].name | awk -F. '{OFS="."; $NF+=1; print $0}'`

          git tag -a ${VERSION} -m "new release"

          go list -m github.com/kachaje/libsvm-go@${VERSION}
